import { PageTitle } from '@/components/page-title'
import { Metadata } from 'next';
import Head from 'next/head';
import React from 'react'




const Dashboard = () => {

  // const metadata: Metadata = {
  //   title: "Database Configuration",
  //   description: "Generated by create next app",
  // };
  return (
    <div>
      <Head>
        <title>
          Dashboard
        </title>
      </Head>
      <PageTitle title='Dashboard'/>
    </div>
  )
}

export default Dashboard

